# A First Neural Network

### Reviewing our Hypothesis Function

* inputs
* weights and bias
* fire or not

<img src="neuron-general-2.png" width="40%">

We saw that this hypothesis function really consists of two components:
1. Linear layer which can return any positive or negative or number, and
2. Activation function which translates that output to a number between 1 and 0 (to represent firing or not).

> Mathematically, we represented the neuron's linear function and activation function as the following:

$z(x) = w_1x_1 + w_2x_2 + b = w \cdot x + b $

$ \sigma(z) = \frac{1}{1 + e^{-z}} $

And we can represent this as code like so:  

In [1]:
def linear_layer(x):
    return w.dot(x) + b

In [2]:
def sigmoid_activation(z):
    return 1/(1 + torch.exp(-z.float()))

Then we can define some initial weights and a bias.

In [4]:
# weight cell_area 2, weight for cell_concavities 1
import torch
w = torch.tensor([2., 1.])
b = torch.tensor(-10.)

And pass through a vector $x$, which represents the efeeatures of an observation.

In [5]:
import torch
# cell area is 3, and cell concavities is 4
x = torch.tensor([2., 4.])

So to get the out from the linear layer, we pass our data through the linear layer.

In [6]:
z = w.dot(x) + b
z

tensor(-2.)

And then pass that output to the activation layer, which returns a value between 0 and 1.

In [7]:

linear_layer(x):
sigmoid_activation(z)

tensor(0.1192)

### Translating to a neural net

In [29]:
import torch.nn as nn

net = nn.Sequential(
    nn.Linear(2, 1),
    nn.Sigmoid()
)

In [30]:
x = torch.tensor([2., 4.])
x

tensor([2., 4.])

In [31]:
net(x)

tensor([0.8151], grad_fn=<SigmoidBackward>)

In [32]:
net[0].weight

Parameter containing:
tensor([[0.5225, 0.0173]], requires_grad=True)

In [33]:
net[0].bias

Parameter containing:
tensor([0.3692], requires_grad=True)

In [48]:
torch.manual_seed(4)

ll = nn.Linear(2, 1)

ll.weight

Parameter containing:
tensor([[-0.6260,  0.0929]], requires_grad=True)

Neural network with just a single neuron.

In [2]:
import torch
x = torch.tensor([2., 4.])

In [1]:
import torch.nn as nn

net = None

In [2]:
# net(x)

* Take our data

In [32]:
# cell area is 3, and cell concavities is 4
x = torch.tensor([2., 4.])

In [34]:
net(x)

tensor([0.7962], grad_fn=<SigmoidBackward>)

So $x$ represents the features of a single observation.  And we can see our neural network's predictions with the following:

In [16]:
net(x)

tensor([0.0642], grad_fn=<SigmoidBackward>)

$z(x) = w \cdot x + b$

$ \sigma(z) = \frac{1}{1 + e^{-z}} $

### Understanding the Components

Ok, so we just saw how we can create a neural network in Pytorch.

In [1]:
import torch.nn as nn

net = nn.Sequential(
    nn.Linear(2, 1), # length of each vectors, 
    nn.Sigmoid()
)

net

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
  (1): Sigmoid()
)

* Breaking down the linear layer

$z(x) = w_1x_1 + w_2x_2 + b$

###  Random Weights

In [33]:
ll = nn.Linear(2, 1)
ll.weight

Parameter containing:
tensor([[-0.6047,  0.2253]], requires_grad=True)

* Seed manually to make sure start off with same weight

In [11]:
torch.manual_seed(5)
ll = nn.Linear(2, 1)

ll.weight

Parameter containing:
tensor([[ 0.4670, -0.5288]], requires_grad=True)

### Creating multiple neurons

* What does it mean to create multiple neurons?

In [50]:
nn.Linear(2, 1).weight

Parameter containing:
tensor([[0.2932, 0.2992]], requires_grad=True)

In [51]:
ll_3 = nn.Linear(2, 3) # 3 neurons of length 2

ll_3.weight

Parameter containing:
tensor([[-0.2718,  0.6800],
        [-0.6926, -0.0480],
        [-0.0560,  0.5016]], requires_grad=True)

In [52]:
x = torch.tensor([2., 4.])

In [53]:
ll_3(x)

tensor([ 2.1093, -1.3911,  1.8602], grad_fn=<AddBackward0>)

Finally, the sigmoid function takes the output from our linear function and passes it through our sigmoid function.

In [26]:
sigmoid = nn.Sigmoid()

In [27]:
z = ll_3(x)
sigmoid(z)

tensor([0.0688, 0.1676, 0.6037], grad_fn=<SigmoidBackward>)

And then our `nn.Sequential` function packages up our two functions, and passes the output from one layer into the next layer.

In [18]:
import torch.nn as nn

net = nn.Sequential(
    nn.Linear(2, 1),
    nn.Sigmoid()
)

net

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
  (1): Sigmoid()
)

### Summary

In this lesson, we saw how to create a neural network -- with a single neuron -- in Pytorch.

In [64]:
net = nn.Sequential(
    nn.Linear(2, 1),
    nn.Sigmoid()
)

We saw that with the linear layer, we specify the number of input features, and the number of neurons -- where each neuron consists of a weight vector and a bias term.

In [65]:
layer = nn.Linear(2, 1)
layer._parameters

OrderedDict([('weight',
              Parameter containing:
              tensor([[-0.2977,  0.1892]], requires_grad=True)),
             ('bias',
              Parameter containing:
              tensor([-0.3397], requires_grad=True))])

And we saw that we can pass a feature vector to this layer, and it will apply the linear function $z(x) = w \cdot x + b$.

In [66]:
x

tensor([2., 4.])

In [67]:
ll(x)

tensor([0.1087], grad_fn=<AddBackward0>)

And finally that if we pass the feature vector to the neural net, that it will pass the feature vector through the linear layer, and that output to the sigmoid activation function to produce a prediction between 0 and 1 expressing the strength of the neuron firing.

In [68]:
net(x)

tensor([0.2172], grad_fn=<SigmoidBackward>)